<?php

namespace AppBundle\Repository;

/**
 * WidthRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WidthRepository extends \Doctrine\ORM\EntityRepository
{
}
